### ISSUE TITLE
PCA9685 board

### ISSUE THREAD

**Issue by muzi-15** [bithollow/bithollow.github.io#1]

**Comment by muzi-15** [comment]
detailed list:
1. pca9685 Tssop28
2. convert to DIP 28 board
3. resistance   1K,1.5K,2.2K,4.7K,8.6K,10K
4. bread board

**Comment by muzi-15** [comment]
order form as follows:
1. 3.resistance: x20
    http://detail.tmall.com/item.htm?id=39813854420&spm=a1z09.2.9.25.MAsywv&_u=835sn0n1803
2. TSSOP28 TO DIP converter x5
    http://detail.tmall.com/item.htm?id=25072296568&spm=a1z09.2.9.40.MAsywv&_u=835sn0n20f2
3. PCA9685 x5
     http://detail.tmall.com/item.htm?id=41866364083&spm=a1z09.2.9.10.MAsywv&_u=835sn0n9864

**Comment by onceme** [comment]
could you move this issue to manifests.git?

**Comment by onceme** [comment]
This issue has finished and it is in the wrong place. I shall close it.
